# action.yaml
name: 'S3 Push'
description: 'create zip from source code and push to specified s3 location'
inputs:
  ref:
    description: 'git ref'
    required: true
  key:
    description: 'key id'
    required: true
  secret:
    description: 'secret'
    required: true
runs:
  using: 'composite'
  steps:
    - run: filename=`basename ${{ inputs.ref }}`
      shell: bash
    - run: zip -r ../$filename.zip . -x ".*" && mv ../$filename.zip .
      shell: bash
    - run: mkdir .aws && echo "[default]\nAWS_ACCESS_KEY_ID=${{ inputs.key }}\nAWS_SECRET_ACCESS_KEY=${{ inputs.secret }}" > .aws/credentials
      shell: bash
    - run: docker run --rm -t -e AWS_REGION=eu-west-2 -v `pwd`.aws:/root/.aws -v `pwd`:/work  ckemper/gha-s3push -b buzz-kemper-arq -f $filename.zip
      shell: bash
