# action.yaml
name: 'S3 Push'
description: 'create zip from source code and push to specified s3 location'
inputs:
  key:
    description: 'key id'
    required: true
  secret:
    description: 'secret'
    required: true
runs:
  using: 'composite'
  steps:
    - run: zip -r ../TREK.zip . -x ".*" && mv ../TREK.zip .
      shell: bash
    - run: |
        echo "hello"
        echo "hello again"

      shell: bash
